export const INIT_LIST_OF_PEOPLE = 'PEOPLE/INIT_LIST_OF_PEOPLE';
export const ADD_NEW_USER = 'PEOPLE/ADD_NEW_USER';
export const CREATE_NEW_USER = 'USER/CREATE_NEW_USER';
export const DELETE_PERSON = 'PEOPLE/DELETE_PERSON';
