export const INIT_LIST_OF_PEOPLE = 'PEOPLE/INIT_LIST_OF_PEOPLE';
export const ADD_NEW_PERSON = 'PEOPLE/ADD_NEW_PERSON';
export const LOGOUT_USER = 'PEOPLE/LOGOUT_USER';
export const SET_USER = 'USER/SET_USER';
export const REMOVE_USER = 'USER/REMOVE_USER';
export const DELETE_PERSON = 'PEOPLE/DELETE_PERSON';
